### ISSUE TITLE
Determine why the main images load so slowly

### ISSUE THREAD

**Issue by ejcer** [MandWdevclub/MandWdevclub.github.io#9]
Might just be an inescapable compromise for using github's CDN, or we might be able to optimize our static contents some how.

**Comment by ghost** [comment]
The size of the `code_background.png` image is nearing 2MB, so the
initial loading of it will be slow on most connections. I'd just
replace it with another image, or remove it all together.

**Comment by ejcer** [comment]
ah darn, I was afraid of that. Well, I can't think of something that looks as cool as that, so I'd prefer to keep it for now

**Comment by ejcer** [comment]
Closing this for now since it seems resolved for now. Anyone, please revive it for further discussion if you'd like
